#!/usr/bin/env bash
# --------------------------------------------------------------------------------
# Script : Condicionais
# Descrição : exemplos de testes de expresão condiocionais
# Versão :
# autor : Carlos Junior <chjunior05@gmail.com>
# Data :03/04/2024
# Licença : GNU/GPL v3.0
#-------------------------------------------------------------------------------
# Uso:
#------------------------------------------------------------------------------

clear

# Mensagem...
echo 'Iremos compara o número que o usuario digita com o número 5'

read -p 'Digite algum número de 1 a 10:' numero

# Tratar erros...
[[ ! $numero =~ ^[0-9]+$ ]] && echo "Erro! Digite um número! " && exit 1

[[ $numero -gt 10 || $numero -le 0 ]] && echo "Erro! Seu número deve está entre 1 e 10 " && exit 1


#Respostas Normais

# -eq = equal
[[ $numero -eq 5 ]] && echo "Seu número é igual a 5 ! " && exit 0

# -lt = less than

[[ $numero -lt 5 ]] && echo "Seu número é menor que 5 ! " && exit 0

# -gt = greater than
[[ $numero -gt 5 ]] && echo "Seu número é maior que 5 !" && exit 0
